# Site settings
title: Fractal Pixels
email: admin@fractalpixels.com
description: An independent game development and programming blog.
baseurl: ""
url: "https://www.fractalpixels.com" 
twitter_username: Fractal_Pixels
github_username:  LeeCombs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
kramdown:
  parse_block_html: true
  
# Disqus comments
disqus:
    shortname: fractalpixels

# Google analytics
google_analytics: UA-119758708-1

# generate social links in footer
social_links:
  twitter: Fractal_Pixels
  github: LeeCombs
  rss: rss
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
