# Site settings
title: Fractal Pixels
email: admin@fractalpixels.com
description: An independent game development and programming blog.
baseurl: ""
url: "https://www.fractalpixels.com" 
twitter_username: Fractal_Pixels
github_username:  LeeCombs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  
# Disqus comments
disqus:
    shortname: fractalpixels

# Google analytics
google_analytics: UA-119758708-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
